# Generated by Django 5.1.1 on 2024-09-17 08:09

import django.db.models.deletion
import phone_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='UserBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, unique=True, verbose_name='ID Телеграма')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Телефон', max_length=31)),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('status', models.CharField(choices=[('owner', 'Владелец сервиса'), ('user', 'Пользователь'), ('admin', 'Админ'), ('seller', 'Продавец'), ('delivery', 'Доставщик')], default='user', max_length=10, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='static/products/', verbose_name='Изображение')),
                ('status', models.CharField(choices=[('active', 'Актуальный'), ('archived', 'Архивный')], default='active', max_length=10, verbose_name='Статус')),
                ('categories', models.ManyToManyField(to='tg_bot.category', verbose_name='Категории')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.CharField(max_length=200, verbose_name='Адрес доставки')),
                ('desired_delivery_date', models.DateTimeField(verbose_name='Дата и время желаемой доставки')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания заказа')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('in_work', 'В работе'), ('in_delivery', 'В доставке'), ('delivered', 'Выдан клиенту'), ('cancelled', 'Отменен')], default='created', max_length=12, verbose_name='Статус заказа')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время выдачи товара клиенту')),
                ('delivery_comments', models.TextField(blank=True, null=True, verbose_name='Комментарии к доставке')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_bot.product', verbose_name='Товар')),
                ('delivery_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_orders', to='tg_bot.userbot', verbose_name='Доставщик')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_orders', to='tg_bot.userbot', verbose_name='Менеджер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to='tg_bot.userbot', verbose_name='Пользователь')),
            ],
        ),
    ]
