# Generated by Django 5.1.1 on 2024-09-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbot',
            name='status',
            field=models.CharField(choices=[('owner', 'Владелец сервиса'), ('user', 'Пользователь'), ('admin', 'Админ'), ('manager', 'Менеджер'), ('delivery', 'Доставщик')], default='user', max_length=10, verbose_name='Статус'),
        ),
    ]
