# Generated by Django 5.1.1 on 2024-09-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0005_alter_category_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Повод')),
            ],
            options={
                'verbose_name': 'Категория повода',
                'verbose_name_plural': 'Поводы',
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='tg_bot.event', verbose_name='Категории'),
        ),
    ]
