# Generated by Django 5.1.1 on 2024-09-17 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0008_pricerange'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceRange',
        ),
    ]
