# Generated by Django 5.1.1 on 2024-09-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0008_pricerange_order_comment_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('inWork', 'В работе'), ('inDelivery', 'В доставке'), ('delivered', 'Выдан клиенту'), ('cancelled', 'Отменен')], default='created', max_length=12, verbose_name='Статус заказа'),
        ),
    ]
