# Generated by Django 5.1.1 on 2024-09-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0009_delete_pricerange'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=300, verbose_name='Описание'),
        ),
    ]
