# Generated by Django 5.1.1 on 2024-09-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0011_pricerange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='desired_delivery_date',
            field=models.DateTimeField(verbose_name='Когда доставить'),
        ),
    ]
