# Generated by Django 5.1.1 on 2024-09-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0012_alter_order_desired_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('inwork', 'В работе'), ('indelivery', 'В доставке'), ('delivered', 'Выдан клиенту'), ('cancelled', 'Отменен')], default='created', max_length=12, verbose_name='Статус заказа'),
        ),
    ]
